FROM alpine:3.21

RUN apk add --no-cache openssh-server shadow util-linux \
  && adduser -D -u 1000 -s /bin/sh ccusage \
  && usermod -p '*' ccusage

COPY deploy/emulation/ccusage-stub.sh /usr/local/bin/ccusage
COPY deploy/emulation/machine-entrypoint.sh /usr/local/bin/machine-entrypoint
RUN chmod 0755 /usr/local/bin/ccusage /usr/local/bin/machine-entrypoint

ARG MACHINE_SEED=1
ENV MACHINE_SEED=${MACHINE_SEED}
ENTRYPOINT ["/usr/local/bin/machine-entrypoint"]
