FROM alpine:3.21
RUN apk add --no-cache openssh-keygen
COPY deploy/emulation/keygen-entrypoint.sh /usr/local/bin/keygen-entrypoint
RUN chmod 0755 /usr/local/bin/keygen-entrypoint
ENTRYPOINT ["/usr/local/bin/keygen-entrypoint"]
